parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: ../stages.yml
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        py_versions: ['3.7', '3.8']
        conda_env: 'pipelines-developer.yml'
      osx:
        py_versions: ['3.7', '3.8']
        conda_env: 'pipelines-developer.yml'
      windows:
        py_versions: ['3.7', '3.8']
        conda_env: 'pipelines-developer.yml'
    deploy: true
    conda_label: 'main'
    release: true
